- src/main/kotlin/org/javacs/kt/classpath/gradleDependencyResolver.kt
This is a sort of proof-of-concept / check if this functionality is desired. If so, I'll clean it up and incorporate any feedback
The current version of the project misses some of the necessary dependencies in Android projects - but it's possible there's a better way to get them than with a custom Gradle task
> Initial support for Android projects

- syntaxes/Kotlin.tmLanguage.json
This is to address [Issue #49](https://github.com/fwcd/KotlinLanguageServer/issues/49)
> Highlight 'field' as a keyword.

- vscode-extension-src/extension.ts
Displays while the language server is starting. Can be used as a basis for people to see how to add further status bar items. 
Tried using notifications between the server and client, have gotten it to work with a typescript language server, wouldnt work with this Kotlin lang server for some reason
> Added a status bar item

- package-lock.json
- package.json
- src/main/kotlin/org/javacs/kt/Config.kt
- src/main/kotlin/org/javacs/kt/KotlinLanguageServer.kt
- src/main/kotlin/org/javacs/kt/KotlinTextDocumentService.kt
- src/main/kotlin/org/javacs/kt/KotlinWorkspaceService.kt
- src/main/kotlin/org/javacs/kt/Main.kt
didChangeConfiguration should be changed to seamlessly handle updating all possible future changes without having to add a new line per config setting
> Added setting to update debounce time

- server/src/main/kotlin/org/javacs/kt/KotlinTextDocumentService.kt
- server/src/main/kotlin/org/javacs/kt/definition/GoToDefinition.kt
- server/src/test/kotlin/org/javacs/kt/DefinitionTest.kt
- server/src/test/kotlin/org/javacs/kt/LanguageServerTestFixture.kt
- server/src/test/resources/definition/GoToProperties.kt
I'm not 100% sure about how the formatting in this project should be, sorry.
IntelliJ with editorconfig did its best :)
> Jump to name of declaration when using goto-definition

- server/src/main/kotlin/org/javacs/kt/completion/RenderCompletionItem.kt
Closes #103, this PR just uses the code snippet provided in the issue.
> Provide parameter names when auto completing functions

- server/src/main/resources/projectClassPathFinder.gradle
Resolves #164 and totally stolen from @ArtemGr from that issue
> Fix Android build classes location

- server/src/main/kotlin/org/javacs/kt/KotlinTextDocumentService.kt
- server/src/main/kotlin/org/javacs/kt/SourceFiles.kt
> Fix `formatOnSave` by try reading the content from memory first

- EDITORS.md
Add notes for some unwanted side effects.
coc is not working without any syntax highlighter
> Add notes in EDITORS.md

- server/src/main/kotlin/org/javacs/kt/completion/Completions.kt
It's just the same method like import, but filtered.
So only package names will be shown. :)
> Implement package completion

- server/src/main/kotlin/org/javacs/kt/KotlinLanguageServer.kt
- server/src/main/kotlin/org/javacs/kt/KotlinTextDocumentService.kt
- server/src/main/kotlin/org/javacs/kt/semantictokens/SemanticTokens.kt
- server/src/main/kotlin/org/javacs/kt/util/PsiUtils.kt
- server/src/test/kotlin/org/javacs/kt/LanguageServerTestFixture.kt
- server/src/test/kotlin/org/javacs/kt/SemanticTokensTest.kt
- server/src/test/resources/semantictokens/SemanticTokens.kt
- shared/src/main/kotlin/org/javacs/kt/classpath/GradleClassPathResolver.kt
This is an early-stage draft of support for semantic highlighting:
> Add support for semantic tokens/highlighting

- .github/workflows/build.yml
- .github/workflows/deploy.yml
Mainly for using `gradle-build-action` to speed up build on CI, and bump action versions by the way.
https://github.com/gradle/gradle-build-action
> Optimize CI a bit

- server/src/main/kotlin/org/javacs/kt/compiler/Compiler.kt
> Depend on Kotlin's implementation of parsing JVM target

- grammars/Kotlin.tmLanguage.json
Fix for https://github.com/fwcd/kotlin-language-server/issues/412
> Highlight value keyword for value class

- shared/src/main/kotlin/org/javacs/kt/classpath/CachedClassPathResolver.kt
- shared/src/main/kotlin/org/javacs/kt/database/DatabaseService.kt
This fixes the typo and bumps the database version.
> Fix typo in `buildFileVersion` column

- .github/labeler.yml
- .github/workflows/labeler.yml
This adds an auto-labeler for many of our labels to quickly categorize PRs.
> Add PR auto-labeler

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- .github/workflows/docker.yml
Mostly a dummy PR to smoke-test the new labeler.
> Bump `actions/checkout` to v4

- server/src/test/kotlin/org/javacs/kt/CompiledFileTest.kt
- server/src/test/kotlin/org/javacs/kt/CompilerTest.kt
- server/src/test/kotlin/org/javacs/kt/CompletionsTest.kt
- server/src/test/kotlin/org/javacs/kt/DefinitionTest.kt
- server/src/test/kotlin/org/javacs/kt/DiagnosticTest.kt
- server/src/test/kotlin/org/javacs/kt/DocumentHighlightTest.kt
- server/src/test/kotlin/org/javacs/kt/DocumentSymbolsTest.kt
- server/src/test/kotlin/org/javacs/kt/FormatTest.kt
- server/src/test/kotlin/org/javacs/kt/GradleDSLScriptTest.kt
- server/src/test/kotlin/org/javacs/kt/JavaToKotlinTest.kt
- server/src/test/kotlin/org/javacs/kt/OverrideMemberTest.kt
- server/src/test/kotlin/org/javacs/kt/RenameTest.kt
- server/src/test/kotlin/org/javacs/kt/ResolveMainTest.kt
- server/src/test/kotlin/org/javacs/kt/SimpleScriptTest.kt
Hi, this is my first time to contribute to this repo! 
I've removed unused imports in tests as far as I could find. 
If these are intentional, please discard the pull request. Thanks!
> Remove unused imports in tests

- server/src/main/kotlin/org/javacs/kt/Main.kt
I found a small typo in the comment while I was reading code :D
> Fix small typo

- EDITORS.md
Add how to integrate with [helix](https://helix-editor.com/)
> Add helix to editor configuration

- .github/workflows/build.yml
- .github/workflows/deploy.yml
the origin ci is deprecated, we need to sync to new ci here
> chore: update gradle ci
