src/main/kotlin/org/javacs/kt/classpath/gradleDependencyResolver.kt

I've got a very fairly large project where querying the Gradle task for dependencies apparently generates more output than fits in a standard buffer - waiting on the process before draining the input creates a deadlock.

Gradle task handles output that overflows buffer

---

src/main/resources/classpathFinder.gradle

Simplify some of the code around retrieving the android jar file
The Android plugin already knows the location of the Android jar file. Grabbing it this way should also be more resilient to future Android SDK changes.

Simplify retrieval of the android jar file

---

src/main/kotlin/org/javacs/kt/classpath/gradleDependencyResolver.kt

I noticed this test failing on Windows 10 while trying to parse the console output from the temporary gradle file. The modification to the regex will work for both `\r\n` and `\n` line breaks coming from the stdout.

Added support for `\r\n` line breaks in Gradle CLI dependency parsing.

---

src/main/resources/classpathFinder.gradle

Intermediate dependencies (e.g. R.class) were hard coded to the debug
build flavor. This commit fixes this by outputing the intermediate paths
for all flavors.
Note that there is no way to output only the dependencies for the flavor
being build at the moment. This script is executed before any particular
build (e.g. assembleDebug) is executed so we cannot know before hand
what deps to load. Fortunatelly most of the time, dependencies do not
conflict between flavors so loading them all should not be an issue
(most of the time).

Fix intermediate deps for flavors other than debug.

---

src/main/resources/classpathFinder.gradle

Newer versions of the Android plugin move the R.class files into a different folder. We support that new location here so that completion works properly
I made a separate merge request than #43 so that they could be independently evaluated but forgot to only include one commit. Let me know if this needs to be rebased to fix this :)
Fixes #7

Support newer android plugins

---

build.gradle
src/main/kotlin/org/javacs/kt/KotlinTextDocumentService.kt
src/main/kotlin/org/javacs/kt/symbols/symbols.kt
src/test/kotlin/org/javacs/kt/DocumentSymbolsTest.kt

3 places needed work to accomodate for changed method signatures with new `org.eclipse.lsp4j.jsonrpc.messages.Either` in their return types

Updated org.eclipse.lsp4j to 0.5.0 from 0.4.1

---

src/main/kotlin/org/javacs/kt/definition/goToDefinition.kt
src/main/kotlin/org/javacs/kt/externalsources/ClassInJar.kt

Java sources that exist in the jar files downloaded by gradle can now be opened
They are placed in `$TMP_DIR/<relative_path_in_jar>/<file>.java`
If java file not found, proceed with usual class file finding
Uncommented section in `goToDefinition.kt` as it doesnt seem to be causing any issues as seen so far
Sample used: `org.eclipse.lsp4j-0.5.0.jar`
I understand that this is still a very rough implementation which probably fails under edge cases. Naturally, #45 is resurfaced as a result if the java files dont exist, so this should probably not be merged until such time as we can sort that out.
Unfortunately, as the files extracted are Java files, we're at the whim of the features of the Java vscode extension after that if we're wanting to go down the chain of imports :smile:

[WIP] Open java sources found in jar as downloaded by gradle

---

src/main/kotlin/org/javacs/kt/classpath/findClassPath.kt

The code to remove duplicate stdlib imports in in `ensureStdlibInPaths` can get confused with JDK-specialized stdlibs (e.g. `kotlin-stdlib-jdk7`).  These specialized instances only implement a subset of the Kotlin standard library that's optimized for that deployment target (or so it appears?), and need another library to implement the rest of the library (seems to be `kotlin-stdlib-common` for me).  
Current code may end up grabbing _just_ `kotlin-stdlib-jdk7` (or whatever) if it comes up first in the dependencies list, which leaves us missing most of the standard library methods.
PR code tries to pull in only one of each 'kind' of jar, and only the newest of each.  That's a pretty shallow heuristic but it seems to solve issues I've been seeing, which I think are identical to issues #56 …

Improved Kotlin standard library dependency resolution

---

package-lock.json
src/main/kotlin/org/javacs/kt/completion/Completions.kt
src/test/kotlin/org/javacs/kt/CompletionsTest.kt

Showing function/class name and now also list of parameters as provided to us in completion list. More of a preference thing, i like that one can see all differences in the overloads at a glance unlike previously where one would only see the parameter list of the selected completion.
Tested with functions/methods and class constructors
Before:
After:

Parameter lists in completion labels

---

src/main/kotlin/org/javacs/kt/completion/Completions.kt
src/test/kotlin/org/javacs/kt/CompletionsTest.kt
src/test/resources/completions/Enum.kt

Fix for https://github.com/fwcd/KotlinLanguageServer/issues/63
The loading of descriptors was stopping after looking at the companion object when it should have also looked at the enum for more autocomplete options.  This is my first PR here so feel free to recommend a better implementation.

Fix autocomplete for enums with companion objects

---

src/main/kotlin/org/javacs/kt/completion/Completions.kt
src/test/kotlin/org/javacs/kt/CompletionsTest.kt
src/test/resources/completions/InstanceMember.kt

(Partly) Fixes https://github.com/fwcd/KotlinLanguageServer/issues/75
Referencing the test:
if there is a call `SomeClass().instanceFoo()` and you place the cursor right after the `F` in `instanceFoo`, you should get the options of `instanceFoo` and `instanceFee` instead of nothing.
Is there any documentation on these Kotlin classes because I have no idea if I'm doing this right at all? The only thing I was judging by was debugging and calling `el.text`, `el.parent.text`, etc and saw that `el.text` returns `instanceFoo`, `el.parent.text` returns `instanceFoo()` but `el.parent.parent.text` returns `SomeClass().instanceFoo()`.  I don't know if this will fix every expression.
I'm guessing a possible refactor would be checking if `el` has any ancestor that is a `KtQualifiedExpression` but not …

provide accurate completions when triggered from the middle of an instance method

---

server/src/main/kotlin/org/javacs/kt/SourceFiles.kt

It seems that in some cases the plugin is trying to resolve files who
are not part of the workspace, due to either their temporary nature, or
other IDE or tool file.
In my case, it was trying to resole files from the vim .undodir
directory, was failing to parse those files due to their binary nature,
and the whole sourceset resolution was failing in consequence.
To avoid that issue add a try catch around the file reading method to
ensure exception are not fired, and the resolution does not break.

Fix an issue when trying to resolve an non source file

---

shared/src/main/kotlin/org/javacs/kt/classpath/BackupClassPathResolver.kt
shared/src/main/kotlin/org/javacs/kt/classpath/FindClassPath.kt
shared/src/main/kotlin/org/javacs/kt/classpath/GradleDependencyResolver.kt
shared/src/main/kotlin/org/javacs/kt/classpath/MavenClassPathResolver.kt
shared/src/main/kotlin/org/javacs/kt/classpath/ShellClassPathFinder.kt
shared/src/main/kotlin/org/javacs/kt/classpath/WithStdlibResolver.kt

I work with a number of repos that use a non-public, proprietary dependency resolution system. To get the language server to find dependencies, I needed a way to run a simple shell command that just returned a colon delimited list of jars. While I was in there, I also did some organization to make this section of code less monolithic.
My first commit adds a new interface, `ClassPathResolver`. Its got one property: `classpaths`. I could have left it as a set of methods, but using an interface adds more semantic meaning.
I then split the existing code into separate files:
1. `GradleClassPathResolver`: All of the existing gradle resolution logic
2. `MavenClassPathResolver`: All of the existing maven resolution logic
3. `WithStdlibResolver`: Existing logic that adds the stdlib to to another …

Organize FindClassPath and add classpath resolution from shell script

---

server/src/main/kotlin/org/javacs/kt/KotlinTextDocumentService.kt

[KotlinTextDocumentService#linting](https://github.com/fwcd/KotlinLanguageServer/blob/master/server/src/main/kotlin/org/javacs/kt/KotlinTextDocumentService.kt#L33) is set to `true` at the [first](https://github.com/fwcd/KotlinLanguageServer/blob/4e28547ffb32edf0ca39db01cef6ef0aeb1c1949/server/src/main/kotlin/org/javacs/kt/KotlinTextDocumentService.kt#L217) of [KotlinTextDocumentService#doLint](https://github.com/fwcd/KotlinLanguageServer/blob/master/server/src/main/kotlin/org/javacs/kt/KotlinTextDocumentService.kt#L215) and then set to `false` at [end](https://github.com/fwcd/KotlinLanguageServer/blob/4e28547ffb32edf0ca39db01cef6ef0aeb1c1949/server/src/main/kotlin/org/javacs/kt/KotlinTextDocumentService.kt#L222) of there.  
But if an exception (e.g. #42) is occurred, it is never set to …

Fix an issue when exception in KotlinTextDocumentService#doLint

---

package.json
server/src/main/kotlin/org/javacs/kt/Configuration.kt
server/src/main/kotlin/org/javacs/kt/KotlinLanguageServer.kt
server/src/main/kotlin/org/javacs/kt/KotlinTextDocumentService.kt
server/src/main/kotlin/org/javacs/kt/KotlinWorkspaceService.kt
server/src/main/kotlin/org/javacs/kt/completion/Completions.kt
server/src/main/kotlin/org/javacs/kt/completion/RenderCompletionItem.kt
server/src/test/kotlin/org/javacs/kt/LanguageServerTestFixture.kt

Provide non-snippet completions if the client does not set the `snippetSupport` flag. Fixes #119.

Add snippet configuration support

---

BUILDING.md

The current build doc is confusing, in that it says "Java 8+ should be installed". 
Most developers (myself included) will take this to mean that _any_ version 8+ will work, yet Java 11 fails with known issues. This PR corrects the language to make it clear that the user needs Java 8, and no other later version actually works yet.

Better build instructions w.r.t Java version

---

server/src/main/kotlin/org/javacs/kt/completion/Completions.kt

It seems that KLS always omit getter/setter in candidates of completion even if it cannot compile.
For example, when completing `Foo.`, KLS returns `obj` as a candidate. But it happens compilation error if applied because `setObj` and `getObj` are static method. Correct candidates are `setObj` and `getObj`
```java
public class Foo {
public static void setObj(Object o) {
// ...
}
public static Object getObj() {
// ...
}
}
```

Omit getter/setter only when it's Java code and instance method

---

BUILDING.md
README.md
editors/README.md
server/src/main/kotlin/org/javacs/kt/completion/Completions.kt
server/src/main/kotlin/org/javacs/kt/j2k/JavaElementConverter.kt
server/src/main/kotlin/org/javacs/kt/j2k/JavaToKotlinConverter.kt
server/src/main/kotlin/org/javacs/kt/j2k/JavaTypeConverter.kt
server/src/main/kotlin/org/javacs/kt/j2k/PlatformTypeConverter.kt
server/src/test/kotlin/org/javacs/kt/JavaToKotlinTest.kt
server/src/test/resources/j2k/JavaJSONConverter.java
server/src/test/resources/j2k/JavaJSONConverter.kt

Since the old J2K was disabled as of #136, this branch contains a new converter that is written from scratch and based on a [PSI](https://www.jetbrains.org/intellij/sdk/docs/basics/architectural_overview/psi_elements.html) visitor.

Rewrite Java-to-Kotlin-converter from scratch

---

server/src/main/kotlin/org/javacs/kt/Compiler.kt
server/src/main/kotlin/org/javacs/kt/SourcePath.kt
server/src/main/kotlin/org/javacs/kt/completion/Completions.kt
server/src/main/kotlin/org/javacs/kt/j2k/JavaToKotlinConverter.kt

To make sure that project services such as the ModuleAnnotationResolver
do no throw concurrency exceptions if an expression happens to be
compiled at the same time as a file.
These issues did occur frequently before, see #42.

Use separate compilation environments for files and expressions

---

server/src/main/kotlin/org/javacs/kt/Compiler.kt

This fixes issues with expect/actual keywords causing errors in VSCode when opening Kotlin multiplatform projects.
todo: should/can the compiler and language args be read from the gradle files?

Add support for multiplatform projects.

---

server/src/main/kotlin/org/javacs/kt/completion/RenderCompletionItem.kt

This follows the convention used by other language servers in VS Code which have synthetic (get/set) properties, like JS, Typescript, and C#. The weird bit here, is that Kotlin compiler identifies all val/vars on a class, even those that are not synthetic, as Properties. Presumably to autogenerate get/set methods on the Java side.
Field icon is a blue box, which is typical for class fields AND class properties. Property is grey nondescript wrench, and it's unclear that it even is or what it does.
I'm unsure what the Property type is used for, but for consistency with how other language servers display fields and synthetic properties within VSCode, the Field enum/icon is the correct behavior.

Use Field icon instead of Property icon for class properties in autocomplete. 

---

.travis.yml
Dockerfile

Fixes #13 
Todo:
It seems that LSP docker images in the wild are using a port to communicate, so that might very well be the way we need to go if we want a docker image for this. Image is currently set up to pretend there's a flag for it even though that doesn't currently exist

WIP: Add basic docker image

---

server/src/main/kotlin/org/javacs/kt/symbols/Symbols.kt
server/src/test/kotlin/org/javacs/kt/DocumentSymbolsTest.kt

As said in the title - returning DocumentSymbol(s) from textDocument/documentSymbol instead of SymbolInformation allows to show the structure of the document. So it would be very nice if DocumentSymbol(s) could be returned. As possible patch is herein.

Using DocumentSymbol instead of SymbolInformation for documentSymbols so that a structure can be provided.

---

shared/src/main/kotlin/org/javacs/kt/classpath/WithStdlibResolver.kt

By excluding kotlin-stdlib-common as a stdlib replacement, we ensure that a valid stdlib is available in the case that the kotlin-stdlib is removed and kotlin-stdlib-common remains. Since the common library isn't a full stdlib, sometimes projects will error in their completion
Resolves #187

Include kotlin-stdlib-common

---

.vscode/settings.json
shared/src/main/kotlin/org/javacs/kt/classpath/MavenClassPathResolver.kt
shared/src/main/kotlin/org/javacs/kt/util/Utils.kt

Hey there! We were seeing the same thing as #180 when our server started up. We figured out that `mvn dependency:list` writes to `stderr` in our case due to some weirdness, and that was causing the call to `Runtime.getRuntime().exec()` to hang forever, since it was blocking until `stderr` was read. This just passes `stderr` along as if it were stdout, which makes the language server work perfectly for us.

fix error where mvn hangs if anything is output to stderr

---

server/src/main/kotlin/org/javacs/kt/CompiledFile.kt
server/src/main/kotlin/org/javacs/kt/Compiler.kt
server/src/main/kotlin/org/javacs/kt/CompilerClassPath.kt
server/src/main/kotlin/org/javacs/kt/KotlinLanguageServer.kt
server/src/main/kotlin/org/javacs/kt/KotlinWorkspaceService.kt
server/src/main/kotlin/org/javacs/kt/SourceFiles.kt
server/src/main/kotlin/org/javacs/kt/SourcePath.kt
server/src/test/kotlin/org/javacs/kt/CompiledFileTest.kt
server/src/test/kotlin/org/javacs/kt/CompilerTest.kt
shared/src/main/kotlin/org/javacs/kt/SourceExclusions.kt
shared/src/main/kotlin/org/javacs/kt/util/URIs.kt
shared/src/main/kotlin/org/javacs/kt/util/Utils.kt

This PR provides (early-stage) support for importing Java classes into Kotlin source code:

Support Java imports

---

server/src/main/kotlin/org/javacs/kt/Compiler.kt

I've touched this code before when enabling multiplatform support. Ran into this problem again when I was getting errors that release coroutines were not enabled.
Updated this spot to just enable all language features.

enable all language features.

---

server/src/main/resources/projectClassPathFinder.gradle

Android project .class path fixes. The compile${variant}JavaWithJavac path only exists in build/tmp now from what I can tell. It may be defunct based on android plugin version.
This fixes missing generated aidl class files, and probably other stuff as well.
Also fixed inconsistent tabs to match the rest of the file.

Add intermediates in the path format intermediates/javac/debug/classes.

---

server/src/test/kotlin/org/javacs/kt/OneFilePerformance.kt
shared/build.gradle
shared/src/main/kotlin/org/javacs/kt/util/URIs.kt
shared/src/test/kotlin/org/javacs/kt/URIsTest.kt

To fix #200,
This PR fixes the whitespace issue that results crashing the server at initialization phase.

Fix whitespace in path crashes the server

---

server/src/test/kotlin/org/javacs/kt/ClassPathTest.kt
server/src/test/kotlin/org/javacs/kt/DefinitionTest.kt
server/src/test/kotlin/org/javacs/kt/ReferencesTest.kt

Kotlin 1.4's type inference caused a regression since some matcher expressions could no longer be type-inferred.
This PR fixes the issue.

Update tests for Kotlin 1.4's new type inference

---

server/src/main/kotlin/org/javacs/kt/symbols/Symbols.kt

This commit removes an arbitrary restriction of 50 symbols on the
workspace/symbol request in favor of spec compliance (no restriction).

Remove workspace/symbol request size restriction.

---

shared/src/main/kotlin/org/javacs/kt/classpath/DefaultClassPathResolver.kt

Recursively calling Files.list has the risk of an infinite loop when there is a symlink from a lower level to a upper level. Files.walk should avoid this.
See also https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#isDirectory-java.nio.file.Path-java.nio.file.LinkOption...-
> By default, symbolic links are followed and the file attribute of the final target of the link is read.

Use Files.walk for recursive listing

---

server/src/main/resources/projectClassPathFinder.gradle

This change resolves #182 on my end.
**WARNING:** I cannot ascertain if this change would work correctly in all cases, especially as some functionality was removed. Feel free to point out any cases I might have missed.
One thing I noticed is that all of the project's compiled classes get added to the classpath after this change (which is kind of the point, as protobuf generated classes are also there). I have not observed any negative effects of this so far.

Use compileClasspath for listing project dependencies

---

server/build.gradle
server/src/main/kotlin/org/javacs/kt/CompiledFile.kt
server/src/main/kotlin/org/javacs/kt/Compiler.kt
server/src/main/kotlin/org/javacs/kt/CompilerClassPath.kt
server/src/main/kotlin/org/javacs/kt/KotlinTextDocumentService.kt
server/src/main/kotlin/org/javacs/kt/KotlinWorkspaceService.kt
server/src/main/kotlin/org/javacs/kt/SourceFiles.kt
server/src/main/kotlin/org/javacs/kt/SourcePath.kt
server/src/main/kotlin/org/javacs/kt/compiler/Compiler.kt
server/src/main/kotlin/org/javacs/kt/diagnostic/ConvertDiagnostic.kt
server/src/main/kotlin/org/javacs/kt/hover/Hovers.kt
server/src/main/kotlin/org/javacs/kt/j2k/JavaElementConverter.kt
server/src/main/kotlin/org/javacs/kt/j2k/JavaToKotlinConverter.kt
server/src/main/kotlin/org/javacs/kt/j2k/JavaTypeConverter.kt
server/src/main/kotlin/org/javacs/kt/position/Position.kt
server/src/main/kotlin/org/javacs/kt/signaturehelp/SignatureHelp.kt
server/src/main/kotlin/org/javacs/kt/symbols/Symbols.kt
server/src/main/kotlin/org/javacs/kt/util/PsiUtils.kt
server/src/test/kotlin/org/javacs/kt/AdditionalWorkspaceTest.kt
server/src/test/kotlin/org/javacs/kt/CompilerFixtures.kt
server/src/test/kotlin/org/javacs/kt/DefinitionTest.kt
server/src/test/kotlin/org/javacs/kt/GradleDSLScriptTest.kt
server/src/test/kotlin/org/javacs/kt/HoverTest.kt
server/src/test/kotlin/org/javacs/kt/LanguageServerTestFixture.kt
server/src/test/kotlin/org/javacs/kt/OneFilePerformance.kt
server/src/test/kotlin/org/javacs/kt/SignatureHelpTest.kt

Tagged diagnostics let language servers attach richer semantic information to diagnostics, e.g. unused variable and deprecation warnings:

Update LSP4J to 0.10.0 and tag diagnostics

---

shared/src/main/kotlin/org/javacs/kt/classpath/DefaultClassPathResolver.kt

This branch rewrites the file walker that looks for build files in a projects to be lazier by cutting off entire branches when finding an ignored pattern.

Walk the file tree lazily while looking for resolvers

---

shared/src/main/kotlin/org/javacs/kt/classpath/DefaultClassPathResolver.kt

This closes #248 
As it is, with a `.gitignore`-file containing eg. `target`, it would ignore the folder `<the-repo>/target`, but not `<the-repo>/moduleA/target`. Added zero-or more glob dir-matcher `**` to fix this.
Also, `.gitignore` may have a `/` suffix, which will not match a Path to the same folder. Added removal of this suffix.
I tested `defaultClassPathResolver(listOf(Paths.get("/path/to/problem/repo"))).classpath`:
Before change: 1 min, 45 s
After change: 7 s
It's still possible to decrease this even further. Some ideas for:
- The code runs `mvn dependency:list -DincludeScope=test` for every `pom.xml` that is not in an ignored directory. For multimodule project, only the root-pom needs to be run, as this will find deps for all modules.
- mvn commands are usually a lot slower than …

fix slow filewalk in some projects

---

shared/src/main/kotlin/org/javacs/kt/classpath/Home.kt

Gradle users can specify where gradle lives via `$GRADLE_USER_HOME`. When this is done, the classpath resolver doesn't check the location set by the env var, but only the default location. This results in a failed build if kotlin is not on `$PATH`.
This PR fixes that by checking for `$GRADLE_USER_HOME` first, and falling back to the default `~/.gradle` if it's not set.
To see the change in action, open [the base repo in gitpod](https://gitpod.io/#https://github.com/fwcd/kotlin-language-server) and run `./gradlew :server:build`. It should fail.
To see the fix in action, open [this repo in gitpod](https://gitpod.io/#https://github.com/daphil19/kotlin-language-server) and run `./gradlew :server:build`. It should succeed.
This closes #254

Refactor gradleHome to check for GRADLE_USER_HOME first

---

server/src/main/resources/projectClassPathFinder.gradle

I found that kotlin-language-server wasn't working for my project, which is an android AAR library.   I looked into it and it seems its because the `libraryVariants` property is not checked.  After this change things work nicely in my project.
Thanks for this btw, works great

Fixed to find dependencies correctly when applied to android library

---

server/src/main/kotlin/org/javacs/kt/KotlinLanguageServer.kt
server/src/test/kotlin/org/javacs/kt/LanguageServerTestFixture.kt

With LSP adding support for official progress indicator, we can drop the custom `Initializing Kotlin Language Server...` status indicator in the VSCode and emit more detailed information on the server side, e.g. like this:

Emit progress notifications

---

gradle.properties
server/build.gradle
server/src/main/dist/licenseReport.html
server/src/main/kotlin/org/javacs/kt/Configuration.kt
server/src/main/kotlin/org/javacs/kt/KotlinLanguageServer.kt
server/src/main/kotlin/org/javacs/kt/KotlinTextDocumentService.kt
server/src/main/kotlin/org/javacs/kt/KotlinWorkspaceService.kt
server/src/main/kotlin/org/javacs/kt/SourcePath.kt
server/src/main/kotlin/org/javacs/kt/SymbolIndex.kt
server/src/main/kotlin/org/javacs/kt/completion/Completions.kt
server/src/main/kotlin/org/javacs/kt/index/ExtractSymbolExtensionReceiverType.kt
server/src/main/kotlin/org/javacs/kt/index/ExtractSymbolKind.kt
server/src/main/kotlin/org/javacs/kt/index/ExtractSymbolVisibility.kt
server/src/main/kotlin/org/javacs/kt/index/Symbol.kt
server/src/main/kotlin/org/javacs/kt/index/SymbolIndex.kt
server/src/main/kotlin/org/javacs/kt/progress/LanguageClientProgress.kt
server/src/main/kotlin/org/javacs/kt/progress/Progress.kt
server/src/main/resources/kotlinDSLClassPathFinder.gradle
server/src/test/kotlin/org/javacs/kt/LanguageServerTestFixture.kt

This is some experimental work on indexing the project's globally available symbols in the background and offering completions for them, regardless of whether they have been imported or not:
Todo:
Additionally, this branch introduces a new `Progress` abstraction for emitting progress notifications to the client, if supported.
Future ideas, not in the scope of this PR:
- (#270) Store rendered descriptor previews in symbol index
- (#271) Store location URIs in symbol index
- (#271) Use symbol index for workspace symbols and go-to-definition (may require URIs in symbol records, see above)
- (#272) Reindex project incrementally as local files change
- (#273) Reindex entire project when the compiler is reinstantiated, e.g. due to classpath changes

Index global descriptors and provide completions for unimported symbols

---

server/src/main/kotlin/org/javacs/kt/compiler/Compiler.kt

Seems to fix https://github.com/fwcd/kotlin-language-server/issues/263
[This](https://github.com/JetBrains/kotlin/commit/57a674e9e6be67cce2efa5b7352890e9f970ede4#diff-daf7679f3a63204ff6ee82e5fd4b57888298f44b6a39e1d9ee6ba9ba89b7da91L189-R189) might be why it stopped working. Not actually sure 😐

Fix Go To Definition for symbols inside jars

---

server/src/main/kotlin/org/javacs/kt/CompilerClassPath.kt
server/src/main/kotlin/org/javacs/kt/KotlinLanguageServer.kt
server/src/main/kotlin/org/javacs/kt/KotlinTextDocumentService.kt
server/src/main/kotlin/org/javacs/kt/URIContentProvider.kt
server/src/main/kotlin/org/javacs/kt/definition/GoToDefinition.kt
server/src/main/kotlin/org/javacs/kt/externalsources/JarClassContentProvider.kt
server/src/main/kotlin/org/javacs/kt/externalsources/KlsURI.kt
shared/src/main/kotlin/org/javacs/kt/classpath/BackupClassPathResolver.kt
shared/src/main/kotlin/org/javacs/kt/classpath/ClassPathResolver.kt
shared/src/main/kotlin/org/javacs/kt/classpath/GradleClassPathResolver.kt
shared/src/main/kotlin/org/javacs/kt/classpath/MavenClassPathResolver.kt
shared/src/main/kotlin/org/javacs/kt/classpath/ShellClassPathResolver.kt
shared/src/main/kotlin/org/javacs/kt/classpath/WithStdlibResolver.kt
shared/src/main/kotlin/org/javacs/kt/util/URIs.kt
shared/src/main/kotlin/org/javacs/kt/util/Utils.kt
shared/src/test/kotlin/org/javacs/kt/MavenArtifactParsingTest.kt

This adds supports for source JARs with Maven.
It seems to work fine. I created a data class to hold compiled and source JARs. Source JARs are downloaded asynchronously. The JARs are downloaded using `mvn dependency:sources`.
When a source jar is unavailable we still decompile the bytecode. If the source jar is available, we just open it. This required a new query parameter to be added to the KLS URI, in order for the `jarClassContents` request to be able to know when to decompile and when to fetch the source JAR.
I tested all the features showcased in the README and nothing broke, but I'm sure there's stuff I might have missed. I'll try to test more things if I remember anything I overlooked. If you can think of any other scenarios to test, let me know so I can try them out.
I did not …

Add support for source JARs with Maven

---

server/src/main/kotlin/org/javacs/kt/externalsources/JarClassContentProvider.kt
server/src/main/kotlin/org/javacs/kt/externalsources/KlsURI.kt

Fixes https://github.com/fwcd/kotlin-language-server/issues/297
This ended up taking a lot more trouble than I expected 😬 
So apparently, `Paths.get` fails when a URI scheme is given (at least on Windows). Although we're using the `schemeSpecificPart`, this still includes the `file://` because we're using a KLS URI and only the first `kls:` is removed there.
After fixing this, I got another issue because the path being sent to `withJarPath` is not a KLS URI. I convert it to KLS before returning the new one now.
After this, I noticed the source parameter logic was gone (I think it was removed by accident). I re-added it to the places where it made sense to me.
Finally, for some reason the source parameter cast doesn't work anymore (we were casting from Any to Boolean but it failed, leading …

Fix Go To Definition

---

server/src/main/kotlin/org/javacs/kt/references/FindReferences.kt

The references returned tend to be in a random order; this PR sorts them by file/line number.
E.g., before this change:
After this change:

Sort found references

---

grammars/kotlin.configuration.json

Improves region-comment folding support; fixes #306
`// #region regionName` & `// #endregion` works, but `//region regionName` & `//endregion` doesn't;  
This pull request fixes this.

Improved region-comment folding support; fixes #306

---

server/src/main/kotlin/org/javacs/kt/KotlinLanguageServer.kt
server/src/main/kotlin/org/javacs/kt/KotlinTextDocumentService.kt
server/src/main/kotlin/org/javacs/kt/references/FindReferences.kt
server/src/main/kotlin/org/javacs/kt/rename/Rename.kt
server/src/test/kotlin/org/javacs/kt/LanguageServerTestFixture.kt
server/src/test/kotlin/org/javacs/kt/RenameTest.kt
server/src/test/resources/rename/SomeClass.kt
server/src/test/resources/rename/SomeOtherClass.kt

Fixes https://github.com/fwcd/kotlin-language-server/issues/16
Rename works when you request it on the definition of a symbol, but also when you request it on one of the references. It therefore leverages the existing logic for definitions and references.
While I was testing this, I noticed that the references don't always work (e.g., they work fine for classes but not for method arguments). This obviously has an impact on the rename.

Implement Rename

---

server/src/main/kotlin/org/javacs/kt/KotlinLanguageServer.kt

Send back a RenameOptions object to client if the client capabilities
populate the prepareSupport field. See: https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#renameOptions

Send back prepare provider if supported by client

---

server/src/main/kotlin/org/javacs/kt/KotlinLanguageServer.kt
server/src/main/kotlin/org/javacs/kt/KotlinTextDocumentService.kt
server/src/main/kotlin/org/javacs/kt/SourcePath.kt
server/src/main/kotlin/org/javacs/kt/index/SymbolIndex.kt

Fixes https://github.com/fwcd/kotlin-language-server/issues/272
This seems to work reasonably well for most cases. I only identified a couple of issues so far. I'll describe those at the end.
Up until now, indexing was done when the first file was compiled. The indexing covered the entire project including all the dependencies. After that, no more indexing was performed.
With this new approach, the first time a file is compiled, we index every symbol (including dependencies). The difference now is that on subsequent compilations, the files' declarations are re-indexed. This process is currently removing all the declarations of the changed files and adding the new ones. This might not be the most performant approach (especially since most declarations will be removed just to be added again …

Setup incremental indexing on file changes

---

server/src/main/kotlin/org/javacs/kt/completion/Completions.kt
server/src/test/kotlin/org/javacs/kt/CompletionsTest.kt
server/src/test/resources/completions/When.kt

Finding some of the completioons lacking when completing sealed classes in when statements, for instance:
```
sealed class Test {
class Nested : Test() {}
}
fun test() {
val example: Test = Test.Nested()
when (example) {
is Test._
}
}
```
Won't complete when the cursor is on `_`. It seems like we're missing something whenever we parse those statements. I've attempted to add this completion
Unfortunately, I found that even with completion working I was running into two issues:
* Properties I expected to be present, weren't completing as I expected
* Indexed global symbols were completing when they probably shouldn't have been
In my project, this resulted in a bunch of junk completions that weren't relevant and missing several that were. I'm unsure of how to test for globally indexed …

Fix when is statement

---

shared/src/main/kotlin/org/javacs/kt/classpath/GradleClassPathResolver.kt

There are rare instances, where there is a non-executable "gradlew" next to a build script. In this case the language server will crash when trying to execute "gradlew".
The happens for example when using an openapi generator as this will place a "build.gradle" and a non-executable "gradlew" in the "build/generated" directory as helper files.

Check if gradlew is executable

---

shared/src/main/kotlin/org/javacs/kt/classpath/MavenClassPathResolver.kt
shared/src/main/kotlin/org/javacs/kt/util/ShellPathUtils.kt

Makes the language server work in environments that only have the Maven wrapper. Only requirement is that the mvnw file (or mvnw.cmd on Windows) is executable, and in the same directory as the pom.xml file (which it always is if present). Server still uses mvn binary by default if that one is found, but fallbacks to trying mvnw if it's not.
The `mvnCommand` function might look a bit messy. Originally it did not have the also-statement, but I thought it would be useful for it to be logged if the Maven wrapper was used. If the `findProjectCommandWithName("mvnw", pom)` call is non-null, and the also-block is called, it will be used. Let me know if you would prefer this in a cleaner way, or if there are any issues I've missed.
Fixes #285

Implemented maven wrapper (mvnw) support

---

gradle.properties

Recently, on Neovim's LSP, I noticed that we were indexing seemingly indefinitely. This resulted in consuming all of the RAM on my laptop and freezing the whole thing!  I'm not entire sure what was causing it, but I noticed that bumping our dependencies seemed to solve the problem
This did result in some build errors regarding mixed java version usage, so I dropped our `javaVersion` to 8. If that's unacceptable, I can look for other solutions

Resolves an infinite loop and/or memory leak

---

server/src/main/kotlin/org/javacs/kt/KotlinTextDocumentService.kt
server/src/main/kotlin/org/javacs/kt/codeaction/CodeAction.kt
server/src/main/kotlin/org/javacs/kt/codeaction/quickfix/AddMissingImportsQuickFix.kt
server/src/main/kotlin/org/javacs/kt/codeaction/quickfix/ImplementAbstractFunctionsQuickFix.kt
server/src/main/kotlin/org/javacs/kt/codeaction/quickfix/QuickFix.kt
server/src/main/kotlin/org/javacs/kt/completion/Completions.kt
server/src/main/kotlin/org/javacs/kt/imports/Imports.kt
server/src/main/kotlin/org/javacs/kt/index/SymbolIndex.kt

Implements Add missing import code action. If I'm not misinterpreting the issue, it is what #302 is requesting. it was something I was really wanting myself. To be honest, I've been using the completion functionality to get my imports in order sometimes 😆 
Emacs screenshots incoming. One line (using lsp-ui, code action marked in yellow):
Marking entire file, then run lsp-execute-code-action:
In VSCode, I was not able to screenshot the code-action itself (Command-Space interrupted the quikfix), but as shown in the screenshot here, quickfixes are available:
(it will show the same import as the Emacs screenshots above)
Did a couple of small rewrites to make this new functionality more clean. The most important ones are:
- Extracted the TextEdit creation of imports to its own function (and …

"Add missing import" quick fix Code Action

---

server/src/main/kotlin/org/javacs/kt/KotlinLanguageServer.kt

The folder sync tasks reports that they are in-progress, but not done. This causes some editors like Emacs using lsp-mode to always display them. No matter how long I wait, "Refreshing source path" will always be there, like you can see in my modeline here:
(ignore that the date-part of my modeline is crushed into the notifications. I have been too lazy to fix it)
Example where indexing is happening at the same time:
You will also notice that `folder.name` part of the message is null, which can be a bit confusing. I added Elvis here to take care of business and make it an empty string in these cases 😄 
Have to admit I've been experiencing these issues for quite a long time, and have probably been lazy for not looking into it. Yesterday I had the epiphany that it might be very confusing to …

Folder sync progress notifications never report that they are done ("Refreshing source path" always present in Emacs modeline)

---

server/src/main/kotlin/org/javacs/kt/codeaction/CodeAction.kt
server/src/main/kotlin/org/javacs/kt/codeaction/quickfix/ImplementAbstractMembersQuickFix.kt
server/src/test/kotlin/org/javacs/kt/QuickFixesTest.kt
server/src/test/resources/quickfixes/samefile.kt
server/src/test/resources/quickfixes/standardlib.kt

Extend the quickfix for implement abstract functions to now be abstract members instead (functions + abstract variables).
Fixes #358

Implement abstract members, now includes abstract variables

---

server/src/main/kotlin/org/javacs/kt/codeaction/quickfix/ImplementAbstractMembersQuickFix.kt
server/src/test/kotlin/org/javacs/kt/QuickFixesTest.kt
server/src/test/resources/quickfixes/samefile.kt

Like the title says. Started implementing based upon issue #366. In hindsight I thin the user is currently experiencing another issue I explain in the comment. Still, I think supporting empty body (no brackets) for the "implement abtract members quick fix" is a good quality of life fix that we should do 🙂 
Also did some consistency changes to the quick fix, as it is not implement abstract members (variables + functions).

Support empty body for Implement abstract members quick fix

---

shared/src/main/resources/projectClassPathFinder.gradle

Implements basic dependency resolution for Kotlin multiplatform projects using Gradle, though a bit flawed (see below). Multiplatform projects have a bit of a different structure than what we are used to in regular projects. In one folder (and build.gradle file) there can be several targets. You can read more on that [here](https://kotlinlang.org/docs/multiplatform-discover-project.html).
Have tried a few different projects, mainly (found in #376):
https://github.com/ktorio/ktor-samples/tree/main/chat
Seem to work pretty good, but I see one possible issue:
- The language server does not separate between the different targets, so it will just resolve the dependencies for all of them. That means a frontend target will get completions with dependencies of the backend target and so on. This …

Experimental resolution of dependencies in Kotlin multiplatform projects (Gradle)

---

shared/src/main/kotlin/org/javacs/kt/classpath/BackupClassPathResolver.kt

Found out about this issue after investigating the issue in:
https://github.com/fwcd/vscode-kotlin/issues/101
Usually I just use Maven or Gradle, so I almost never need to have a kotlinc/kotlin install available for the language server. The current language server expects a structure like this: libexec/bin/kotlinc, but that is not always the case. 
Example on my machine. kotlinc in path resolves to /opt/homebrew/Cellar/kotlin/xxx/bin/kotlinc. stdlib lies in /opt/homebrew/Cellar/kotlin/xxx/libexec/lib/. Because kotlinc is resolved to that place, resolving lib like the code does now (before the PR) won't work as there is no lib-directory in the parent directory. We will have to navigate to libexec, and then lib.
Another example is sdkman installs. In that install, the current implementation …

Support different kotlin/kotlinc install directory setups in backup classpath resolver

---

server/src/main/kotlin/org/javacs/kt/KotlinLanguageServer.kt

Sorry @fwcd , seems like I was too quick to approve a recent PR:
https://github.com/fwcd/kotlin-language-server/pull/381
lsp4j 0.15 causes the following startup issue in many clients:
```
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$recursiveFindRpcMethods$2(GenericEndpoint.java:83)
at org.eclipse.lsp4j.jsonrpc.services.AnnotationUtil.findDelegateSegments(AnnotationUtil.java:32)
at org.eclipse.lsp4j.jsonrpc.services.AnnotationUtil.findDelegateSegments(AnnotationUtil.java:28)
at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.recursiveFindRpcMethods(GenericEndpoint.java:74)
at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.<init>(GenericEndpoint.java:54)
at …
```

URGENT: Fix startup issue for language server caused by lsp4j 0.15 upgrade

---

server/src/main/kotlin/org/javacs/kt/KotlinProtocolExtensionService.kt
server/src/main/kotlin/org/javacs/kt/KotlinProtocolExtensions.kt
server/src/main/kotlin/org/javacs/kt/codeaction/quickfix/ImplementAbstractMembersQuickFix.kt
server/src/main/kotlin/org/javacs/kt/overridemembers/OverrideMembers.kt
server/src/test/kotlin/org/javacs/kt/OverrideMemberTest.kt
server/src/test/resources/overridemember/OverrideMembers.kt

Override any member that is currently not implemented in the current class. This includes open functions, functions with default implementations, open members, abstract stuff etc. The main difference here is that this is general override member functionality, NOT JUST abstract members like the quick fix does. This is super useful for cases where you need to override a default implementation (e.g toString, Thread run, lsp4j interface methods like in TextDocumentService etc.), NOT just the unimplemented abstract ones. For me it would be super useful for my day job using Kotlin 😄 Having to google api docs to find signatures are a pain in the ass just for doing simple stuff like this. 
Two small issues:
- Implicit Any/Object methods does not seem to work. I can't really figure out why. The …

General override member(s) functionality

---

shared/src/main/kotlin/org/javacs/kt/classpath/BackupClassPathResolver.kt

In https://github.com/fwcd/vscode-kotlin/issues/101, a user was using snap to install Kotlin. In my last classpath-resolving-fix PR, I could not get snap working (I mostly use M1 Macs these days, which is ARM and have issues installing the kotlin package as it is only provided for x86/x64). Today I found an older machine (x86), and experimented with snap and installed kotlin that way. I could not resolve the location of stdlib directly using the location of kotlinc. kotlinc resolved to some weird snap-location, and stdlib jars seems to be located in `/snap/kotlin/current/lib/`. We know from the issue I linked to, and the output the user gave, that the implementation (pre other PR) did not resolve the stdlib location.
My solution is to try to resolve a common snap install path directly. …

Resolve kotlin-stdlib.jar from snap install

---

server/src/main/kotlin/org/javacs/kt/codeaction/quickfix/QuickFix.kt
server/src/main/kotlin/org/javacs/kt/util/RangeUtils.kt

Fix issue where implement abstract members code action doesn't show up if you don't mark the entire text. Happens in editors that are not VSCode. The editor I experience it in is Emacs, as discussed in #366. Might be other editors as well, as I've heard from some non-VSCode that they never see any code actions.

Fix issue where code action doesn't show up, unless entire text marked

---

server/src/main/kotlin/org/javacs/kt/CompiledFile.kt
server/src/main/kotlin/org/javacs/kt/KotlinLanguageServer.kt
server/src/main/kotlin/org/javacs/kt/KotlinTextDocumentService.kt
server/src/main/kotlin/org/javacs/kt/highlight/DocumentHighlight.kt
server/src/main/kotlin/org/javacs/kt/references/FindReferences.kt
server/src/main/kotlin/org/javacs/kt/rename/Rename.kt
server/src/test/kotlin/org/javacs/kt/DocumentHighlightTest.kt
server/src/test/resources/highlight/DocumentHighlight.kt
server/src/test/resources/highlight/OtherFile.kt

Really missed this in the Kotlin language server after programming Rust (using rust-analyzer) for a while. Having the same variable highlighted is super useful 🙂 
Fixes #208 
Think I've covered most of the weird edge cases with the unit tests. Also tested manually using Emacs (lsp-mode). One example of how it looks with a global variable being highlighted (the blue'ish):
...and with arguments being highlighted:
...and a class highlighted:
I think you get the point 🙂
Tried to re-use as much existing functionality as possible to make the code small and simple. Feel free to suggest any improvements if you find any. Know we have a bit different coding styles and stuff 🙂 
One weird thing I found: Hovering builtin symbols (e.g, `println` and `Exception`) and comments seems to just mark the …

Implement textDocument/documentHighlight

---

server/src/main/kotlin/org/javacs/kt/compiler/Compiler.kt

Currently, a `settings.gradle.kts` file uses the KotlinBuildScript template. This causes errors in the file. Settings files (`settings.gradle.kts`) works on `org.gradle.api.initialization.Settings` classes, while Build files (`build.gradle.kts`) work on `org.gradle.api.Project` classes. These return different objects, one example being `rootProject`. This object is a `ProjectDescriptor` (having both getter and setter of names and more) in `Settings`, while it is a `Project` in the `Project` class (having only a getter for name). These highlight some of the differences in responsibilities for the two classes.
The issue can be verified by looking at the log-statement produced by the `compileKtFiles`-method in [Compiler.kt](https://github.com/fwcd/kotlin-language-server/blob/86fd15d70b99d34ce …

Make settings.gradle.kts scripts use the KotlinSettingsScript template

---

server/src/main/kotlin/org/javacs/kt/CompiledFile.kt
server/src/main/kotlin/org/javacs/kt/highlight/DocumentHighlight.kt
server/src/main/kotlin/org/javacs/kt/rename/Rename.kt
server/src/test/kotlin/org/javacs/kt/RenameTest.kt
server/src/test/resources/rename/DeclSite.kt
server/src/test/resources/rename/UsageSite.kt

Fix for the rename declaration site part of #320 using the find-declaration-cursor-site fallback I used for highlights in #393.

Rename variable from declaration site

---

shared/src/main/kotlin/org/javacs/kt/SourceExclusions.kt

I'm creating a Kotlin project with `bazel` and vscode. Without excluding this source folder, duplicate generated files end up in the output.

Add Bazel gen files to list of excluded sources

---

server/src/main/kotlin/org/javacs/kt/imports/Imports.kt
server/src/test/kotlin/org/javacs/kt/ImportsTest.kt
server/src/test/resources/imports/Simple.kt

Like the title says.
Fixes #396 
This applies when using the Add missing import quickfix/code action, and when completing a symbol that needs an additional import. It does NOT apply when completing package names in import statements (e.g, `com.c` will still complete to `com.class` and not the backticked version). The reason is that I'm unsure on how we should implement that in the best way. As I see it now, it will require a rewrite of the completion logic for package names. Please let me know if you have a suggestion for how to best implement it, as I might just be a little slow after a week of work (++ other stuff) 🙂

Wrap built-in symbols in package names with backticks when auto-importing

---

gradle.properties
server/src/main/kotlin/org/javacs/kt/compiler/Compiler.kt
server/src/main/kotlin/org/javacs/kt/completion/RenderCompletionItem.kt
server/src/main/kotlin/org/javacs/kt/hover/Hovers.kt
server/src/test/kotlin/org/javacs/kt/OneFilePerformance.kt

Upgrade to kotlin 1.8.0
Seems we still cannot remove usage of deprecated ComponentRegistar at the moment, So added suppression for now which we can handle in 1.9.0 if the `org.jetbrains.kotlin.compiler.plugin.K2PluginRegistrar` is introduced as mentioned in https://youtrack.jetbrains.com/issue/KT-52665

Upgrade to kotlin 1.8.0

---

EDITORS.md

- Adds easy instructions to setup kotlin-language-server with neovim's nvim-lspconfig.
- Allows readers to copy + paste the snippet into their own lua config files.
- Tested with Neovim 0.8.3.

Add neovim lsp config instructions

---

EDITORS.md

Got a bit inspired by @RenFraser in PR #421, so I decided to improve the Emacs instructions with some more useful information. A lot has happened since the original instructions were written 🙂

Add more information on Emacs related configuration and usage

---

server/build.gradle.kts

Just a small commit to fix the only deprecation warning in Gradle. By doing this, we'll be able to bump Gradle to 8+ smoothly.

Fix gradle deprecation warnings

---

.github/workflows/build.yml

In the pipeline we get the following deprecation warning when running on Java 17:
```
'compileTestJava' task (current target is 17) and 'compileTestKotlin' task (current target is 11) jvm target compatibility should be set to the same Java version.
By default will become an error since Gradle 8.0+! Read more: https://kotl.in/gradle/jvm/target-validation
Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain
```
In this PR we set the Java version to the same version as the pipeline is running. This should make it easy to upgrade to Gradle 8.0. @RenFraser , please let me know if you know of a better way to do this! You seem way more knowledgable on Gradle than me 🙂

Set javaVersion property in pipeline/workflow to avoid warnings on Java 17

---

.github/workflows/build.yml
server/src/main/kotlin/org/javacs/kt/resolve/ResolveMain.kt

Why? According to #430 , it seems like there are some caveats for Windows with the language server. I suggest we run the pipeline for both Windows and Ubuntu to combat this. Then we can verify that we don't break anything for Windows (e.g, paths in the shared module and similar). I know that a lot of us uses Linux and Mac OS X instead, and may therefore not have access to Windows machines (I most certainly don't), so having it in the pipeline might help.
The idea behind this PR is also to fix any errors that might happen. 
EDIT: Also added Mac OS X. Building on all major platforms will provide confidence for our users that our language server does indeed build on all major systems. We have had some issues reported with build issues on local machines, so having it in our pipeline can …

Run build pipeline on both Windows, Ubuntu and Mac OS X

---

.github/workflows/build.yml
build.gradle.kts
detekt.yml
detekt_baseline.xml
server/build.gradle.kts

Adds [Detekt](https://github.com/detekt/detekt), a popular open-source static analysis tool to the build.
I've set the build task to depend on running Detekt, rather than having it as a GitHub action. This should catch issues earlier in the development cycle. I've also set the maximum number of issues to be equal to the number of issues that we have at the moment when using the default ruleset. I think it'd be good to start off with the default rules and override them only if they become noise.

Add Detekt to the build

---

build.gradle.kts

I'd noticed that we're configuring detekt twice. 
This commit just keeps the configuration in the one place and also uses better typing for the java version that we pass to the detekt config.

Remove detekt configuration duplication

---

.github/workflows/build.yml
.github/workflows/deploy.yml

Also add a name to clarify that this is only setup. This should resolve the discussion in https://github.com/fwcd/kotlin-language-server/pull/422#discussion_r1122312120.

Remove redundant gradle-build-action step

---

README.md
TROUBLESHOOTING.md

Several people have been experiencing memory issues with the language server for their projects. While this PR doesn't fix anything, I think it can be useful to point people to something they can try to possibly fix the issues on their machines. Therefore I suggest adding a troubleshooting section to the README so it is visible somewhere. Feel free to suggest a better place 🙂 
The vscode description depends on https://github.com/fwcd/vscode-kotlin/pull/121
Issues: #441, https://github.com/fwcd/vscode-kotlin/issues/120 , #403.

Add a troubleshooting section in TROUBLESHOOTING.md for memory issues

---

server/src/main/kotlin/org/javacs/kt/index/SymbolIndex.kt

Doing some profiling and monitoring of the language server with VisualVM these days after several OOM issues. I discovered that when doing completions or other operations querying the symbol index, we get small spikes in heap usage. (will probably be bigger depending on the project size, number of dependencies etc.). These are probably due to having to search the entire in-memory database to find the elements. My idea is to make this slightly more effective by tuning our H2 usage, and I usually tune smaller DBs with an index or two. We search the database on `shortName`, so for me it makes sense to index on that field. My investigations by looking at the memory monitor in VisualVM seems to confirm my hypothesis, as the spikes are way smaller. 
Part one of some tuning. Might be related …

Create a DB index on Symbols table to make searching the SymbolIndex (H2) slightly less memory intensive

---

server/src/main/kotlin/org/javacs/kt/imports/Imports.kt
server/src/test/kotlin/org/javacs/kt/ImportsTest.kt

When importing, we only need to backtick hard keywords. Don't backtick soft keywords and modifiers, as those can be used in package names. You can read more in [the official documentation](https://kotlinlang.org/docs/keyword-reference.html).
Example of the backticking that happens before this PR (notice the line with `PutMapping`):
(not an error per se, but not needed)

Only backtick hard keywords in imports

---

grammars/codeblock.json
grammars/vscode-grammar-dev/package.json

Previously the Kotlin language grammar was injected to `L:markup.fenced_code.block.markdown`, causing the following incorrect rendering of other code blocks in VSCode:
The selector should be changed to a more restricted one of `L:markup.fenced_code.block.markdown - meta.embedded.block`.
Downstream project [vscode-kotlin](https://github.com/fwcd/vscode-kotlin) is also affected.

Fix injectionSelector of Kotlin markdown code block

---

grammars/Kotlin.tmLanguage.json

Fixes #481
Updates the kdoc comments according to the kotlin documentation.
Removes `@deprecated` which is explicitly excluded in the documentation, as well as `@serial` and `@version` which are not listed as supported.
It then adds support for `@constructor`, `@receiver`, `@sample`, `@suppress` and `@property`.
It also supports the `@param[name]` syntax which is given as an example in the docs - no other tags are mentioned to support this name.

Update kdoc keywords according to https://kotlinlang.org/docs/kotlin-doc.html

---

README.md

Very simple PR I intended to do long ago. Needed a break from this repo. Things are going too slow for me to be able to stay motivated, sorry...
Based upon the discussion in #472, I think we should rewrite the line about the debug adapter slightly. If you want to run your code inside your editor/IDE/potato, you still use the debug adapter. One example of this is using the Run/Debug-code lenses and clicking Run.

Clarification on kotlin-debug-adapter role in readme

---

.github/workflows/deploy.yml
.github/workflows/docker.yml

Additionally, update to GHCR, build arm64 images, use the metadata-action to label the images and shorten the image name to `fwcd/kotlin-language-server` (dropping the `/server` suffix).

Extract Docker build into separate workflow

---

platform/build.gradle.kts
server/build.gradle.kts
settings.gradle.kts
shared/build.gradle.kts

The Java platform mechanism[^1] is what we use to pin dependencies across subprojects. According to the docs, the idiomatic way to share a platform is to use regular subprojects[^2], so in the spirit of making our build "more standard", we'll do so too.
[^1]: See the Gradle docs on the Java platform plugin: https://docs.gradle.org/current/userguide/java_platform_plugin.html
[^2]: See the Gradle docs on controlling transitive dependency versions: https://docs.gradle.org/current/userguide/platforms.html#sub:using-platform-to-control-transitive-deps

Move platform to subproject

---

shared/src/main/kotlin/org/javacs/kt/database/DatabaseService.kt

Fixes https://github.com/fwcd/kotlin-language-server/issues/503
We now have a metadata table where we store the database version. If the value stored is the same as the current version, we do nothing. Otherwise, we just delete the entire database and recreate it.
This does not solve https://github.com/fwcd/kotlin-language-server/issues/470 (we can do that in a following PR for clarity)
Note: In the next few weeks, I'll probably also add a command to the VSCode extension to delete the workspace storage directory since that can be helpful at times.

Add Database versioning

---

server/src/main/kotlin/org/javacs/kt/externalsources/ClassContentProvider.kt
shared/src/main/kotlin/org/javacs/kt/classpath/CachedClassPathResolver.kt
shared/src/main/kotlin/org/javacs/kt/database/DatabaseService.kt

This fixes an issue where `null` external source jar paths would have incorrectly been ingested into the database as the string `"null"` and break the definition lookup. See https://github.com/fwcd/kotlin-language-server/issues/470#issuecomment-1745548550 for detailed discussion.
Additionally it bumps the database version to make sure that users' databases get rebuilt with the correct paths.

Fix cached source jar paths

---

shared/src/main/kotlin/org/javacs/kt/database/DatabaseService.kt

This lets us perform backwards-incompatible changes without running the risk that an older version of the language server cannot read it properly.

Require the database to have the exact version required

---

server/src/main/kotlin/org/javacs/kt/CompiledFile.kt

Our `BindingContext`s may span several files, presumably because we compile changed modules in batch and then store the same context across all of these `SourceFile`s:
https://github.com/fwcd/kotlin-language-server/blob/5aa94dad4ef2e2a56b9f6d2907feff52386cf7bf/server/src/main/kotlin/org/javacs/kt/SourcePath.kt#L221-L233
This had the unfortunate side effect that the implicit assumption (?) in methods such as `CompiledFile.referenceFromContext` or `scopeAtPoint` that all entries are in the same file (and thus that it is sufficient to filter by position within the file), does not hold:
https://github.com/fwcd/kotlin-language-server/blob/5aa94dad4ef2e2a56b9f6d2907feff52386cf7bf/server/src/main/kotlin/org/javacs/kt/CompiledFile.kt#L86-L93
Since other files sometimes contain matching scopes, …

Filter by path when querying `BindingContext`

---

detekt.yml

If you take a look at builds in for example #498, you will notice that the test workspaces (e.g, `server/src/test/resources/inlayhints` are affected by detekt scans. I don't think we need to hold this code to the same standard as the main codebase. Sometimes we have minor errors and similar to check that the language server behaves correctly. Detekt will pick up on this and cause issues in the builds. One could off course put this into the baseline, but I think that is a waste of effort. Others might suggest removing it... Instead I suggest we exclude these test workspaces, and keep all the awesome benefits of Detekt 🙂 
Hopefully you agree @fwcd 🙂

Exclude test resource workspaces in detekt analysis

---

grammars/Kotlin.tmLanguage.json

Slightly improve syntax highlighting of functional interfaces (see the `fun? interface` branch in the [classDeclaration](https://kotlinlang.org/docs/reference/grammar.html#classDeclaration) rule).
Before:
After:

Support functional interfaces in Kotlin Textmate grammar

---

shared/src/main/kotlin/org/javacs/kt/classpath/Home.kt

Related to #430
Fixes the Maven repository discovery by checking if the candidate paths have a `/repository` directory. An exception is thrown if no valid repository paths are found. The order of discovery is maintained as before:
- `$MAVEN_REPOSITORY`
- `$MAVEN_HOME`
- `$M2_HOME`
- `$HOME/.m2`

Fix maven repository discovery

---

server/src/main/kotlin/org/javacs/kt/completion/Completions.kt
server/src/test/kotlin/org/javacs/kt/CompletionsTest.kt
server/src/test/resources/completions/InfixFunctions.kt

Closes #446
Adds missing completions for infix functions.

Infix code completion

---

.github/workflows/docker.yml

The Docker workflow gets a few warnings on deprecated behavior. Upgraded the versions, which will hopefully fix most of these warnings. Many actions upgraded to Node16 earlier this year, so makes sense 😛 
Example run:
https://github.com/fwcd/kotlin-language-server/actions/runs/6880796754

Upgrade docker workflow actions versions

---

.github/labeler.yml
.github/workflows/labeler.yml

This updates the PR labeling workflow to v5 and disables `sync-labels`, which should hopefully keep manually added labels intact in the future.

Update PR labeler to v5

---

detekt.yml
server/src/main/kotlin/org/javacs/kt/Configuration.kt
server/src/main/kotlin/org/javacs/kt/KotlinTextDocumentService.kt
server/src/main/kotlin/org/javacs/kt/KotlinWorkspaceService.kt
server/src/test/kotlin/org/javacs/kt/DiagnosticTest.kt
server/src/test/kotlin/org/javacs/kt/HoverTest.kt
server/src/test/kotlin/org/javacs/kt/LanguageServerTestFixture.kt
server/src/test/resources/diagnostic/DiagnosticErrors.kt
server/src/test/resources/diagnostic/Diagnostics.kt

This PR adds two new options, `kotlin.diagnostics.enabled` and `kotlin.diagnostics.level` that can be used by the client to configure if and at which level diagnostics should be emitted by the language server.
Additionally, `kotlin.linting.debounceTime` has been deprecated and renamed to `kotlin.diagnostics.debounceTime`. The old spelling will be kept around for the foreseeable future for backwards compatibility.
Automatically update diagnostics on configuration changes and use the LSP configuration change notification mechanism in the unit test (instead of applying a dummy edit).

Make diagnostic level configurable and add option to disable diagnostics

---

detekt.yml

We now ignore tests in all rule sets, along with `bin` (generated by the VSCode Java extension, which uses the Eclipse JDT language server under the hood where this presumably originates from) and `build`.

Define standard exclusion paths in Detekt configuration

---

server/src/main/kotlin/org/javacs/kt/Configuration.kt
server/src/main/kotlin/org/javacs/kt/KotlinTextDocumentService.kt
server/src/main/kotlin/org/javacs/kt/KotlinWorkspaceService.kt
server/src/test/kotlin/org/javacs/kt/LanguageServerTestFixture.kt

This aligns the `Configuration` structure with the expected JSON keys again.

Rename config object to `inlayHints` for consistency

---

server/src/main/kotlin/org/javacs/kt/CompilerClassPath.kt
server/src/main/kotlin/org/javacs/kt/Configuration.kt
server/src/main/kotlin/org/javacs/kt/KotlinTextDocumentService.kt
server/src/main/kotlin/org/javacs/kt/SourceFiles.kt
server/src/test/kotlin/org/javacs/kt/ScriptTest.kt
shared/src/main/kotlin/org/javacs/kt/ScriptsConfiguration.kt
shared/src/main/kotlin/org/javacs/kt/SourceExclusions.kt

This PR moves the script extension checking logic introduced in #536 to `SourceExclusions`. This lets us test, in a single place, whether a URI is tracked by the source path or not. Additionally, language features (i.e. completions, hovers etc.) are now only provided for included files, previously `KotlinTextDocumentService.recover` forced these files onto the source path, largely subverting the exclusion logic and causing e.g. errors to show up in ignored files, if opened directly.

Model script exclusion via `SourceExclusions` and skip files entirely instead of placing them temporarily on the source path

---

server/src/main/kotlin/org/javacs/kt/KotlinTextDocumentService.kt
server/src/main/kotlin/org/javacs/kt/KotlinWorkspaceService.kt
server/src/main/kotlin/org/javacs/kt/SourceFiles.kt
shared/src/main/kotlin/org/javacs/kt/SourceExclusions.kt

A small follow-up PR to #543. With this, `SourceExclusions` should now be synchronized properly when a `didChangeConfiguration` notification is received. Additionally, the exclusion patterns are now logged, to make it more apparent which files are included or excluded.

Update exclusions upon config changes and log more verbosely

---

server/src/main/kotlin/org/javacs/kt/semantictokens/SemanticTokens.kt
server/src/test/kotlin/org/javacs/kt/SemanticTokensTest.kt
server/src/test/resources/semantictokens/SemanticTokens.kt

Currently, the language server emits a single token for every string literal, which in clients like VSCode covers up interpolations:
Ideally we should probably slice up the string literals to exclude child ranges (that's what SourceKit-LSP seems to do), but for now we are better off not including string literals, thereby deferring the highlighting to e.g. the TextMate grammar:

Remove semantic tokens for string literals (templates)

---

shared/src/main/kotlin/org/javacs/kt/classpath/CachedClassPathResolver.kt
shared/src/main/kotlin/org/javacs/kt/database/DatabaseService.kt

Sometimes the length of path to compiledjar may get longer than 255. 
For example, the path to the cache of this artifact https://mvnrepository.com/artifact/com.ibm.websphere.appserver.api/com.ibm.websphere.appserver.api.security.authorization.saf/1.3.78 may be like following: `/Users/username/.gradle/caches/modules-2/files-2.1/com.ibm.websphere.appserver.api/com.ibm.websphere.appserver.api.security.authorization.saf/1.3.78/5fb520b6711e772218e7f9917d51d1c4347e4cf4/com.ibm.websphere.appserver.api.security.authorization.saf-1.3.78.jar`
It might be better to make this limitation longer.

increase the max length of varchar column of ClassPathCacheEntry table

---

server/src/main/kotlin/org/javacs/kt/signaturehelp/SignatureHelp.kt

I'm using the [Helix Editor](https://helix-editor.com) and when I put my cursor inside a string, and request the help signature it throws an error that `-1` is an invalid value for u32. (helix is written in Rust)
I took a look at the Language Server Protocol Spec and [saw that the `activeSignature` and `activeParameter` are unsigned Integers](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.18/specification/#signatureHelp) according to the spec, so the implementation in helix seems to be correct.
This means these functions should never return a value below 0.
My change sets the activeParameter/activeSignature to `null` if the value is not greater-equals 0, which omits the activeSignature/activeParameter value in the response, as the spec allows, which helix …

Fix negative active signature/parameter

---

.github/workflows/build.yml
server/src/test/kotlin/org/javacs/kt/OverrideMemberTest.kt

This adds CI for Java 21, which should be supported as of #537.

Add Java 21 CI

---

platform/build.gradle.kts

Fixes #550. Java 21 should already be supported and the log message should be fixed in the newer LSP4J version.

Update LSP4J to 0.21.2

---

shared/src/main/kotlin/org/javacs/kt/SourceExclusions.kt

Fixes #294 (partly): Selectively exclude hidden directories instead of all hidden files and dirs (mainly, to make it easier to work with [Teamcity Kotlin DSL](https://www.jetbrains.com/help/teamcity/kotlin-dsl.html#Project+Settings+Structure))

Fixes #294 - selectively exclude hidden directories

---

server/src/main/kotlin/org/javacs/kt/CompiledFile.kt

I've fixed the following issue regarding renaming on Neovim. This change worked on my local machine (macOS).
Fixes #478 
Fixes #499

Change getting file name to URI

---

server/src/main/kotlin/org/javacs/kt/Configuration.kt
server/src/main/kotlin/org/javacs/kt/KotlinTextDocumentService.kt
server/src/main/kotlin/org/javacs/kt/KotlinWorkspaceService.kt
server/src/main/kotlin/org/javacs/kt/formatting/Formatter.kt
server/src/main/kotlin/org/javacs/kt/formatting/FormattingService.kt
server/src/main/kotlin/org/javacs/kt/formatting/KtFmtFormatter.kt
server/src/main/kotlin/org/javacs/kt/formatting/KtfmtFormatter.kt
server/src/main/kotlin/org/javacs/kt/formatting/NopFormatter.kt

Added the following options for ktfmt:
- `kotlin.formatting.formatter`: Can be `ktfmt` (default) or `none` (to disable the formatter)
- `kotlin.formatting.ktFmt.style`
- `kotlin.formatting.ktFmt.indent`
- `kotlin.formatting.ktFmt.maxWidth`
- `kotlin.formatting.ktFmt.continuationIndent`
- `kotlin.formatting.ktFmt.removeUnusedImports`

Add formatting options

---

server/src/test/kotlin/org/javacs/kt/RenameTest.kt

Related to this PR #563.
I thought it would be nice if we have an assertion to check if `textDocument.url` correctly holds `file://` prefix.

Add test of checking file URI prefix for renaming

---

shared/src/main/kotlin/org/javacs/kt/classpath/Home.kt
shared/src/main/kotlin/org/javacs/kt/classpath/MavenClassPathResolver.kt

This fixes a small regression introduced in #518 that caused the language server to crash if no Maven repository was found.

Make maven repository optional again

---

server/src/main/kotlin/org/javacs/kt/CompilerClassPath.kt
server/src/main/kotlin/org/javacs/kt/Configuration.kt
server/src/main/kotlin/org/javacs/kt/KotlinLanguageServer.kt
server/src/main/kotlin/org/javacs/kt/KotlinWorkspaceService.kt
server/src/main/kotlin/org/javacs/kt/compiler/Compiler.kt
server/src/test/kotlin/org/javacs/kt/CompiledFileTest.kt
server/src/test/kotlin/org/javacs/kt/CompilerTest.kt

Code generation as implemented in #334 is currently rather experimental and throws [a lot of exceptions](https://github.com/fwcd/kotlin-language-server/issues/500) on recent Kotlin versions. Until this is addressed, it would be a better user experience if we just disable code generation by default and let advanced users opt-in by setting
```json
{
"kotlin.codegen.enabled": true
}
```
The downside is that Java interoperability will no longer work without this option, but given that it doesn't really seem to work properly in the current state, I believe making it opt-in and experimental for now would be an improvement over the status quo.
cc @daplf

Make code generation (for Java interoperability) opt-in

---

server/src/main/kotlin/org/javacs/kt/CompiledFile.kt
server/src/main/kotlin/org/javacs/kt/compiler/Compiler.kt
server/src/main/kotlin/org/javacs/kt/hover/Hovers.kt
server/src/test/kotlin/org/javacs/kt/CompilerTest.kt

This prevents compilation failures from propagating as exceptions.
Picked from https://github.com/kotlin-community-tools/kotlin-language-server/commit/eadceb7c512d5b2903b51595713132a0b735d515

Return null context if expression fails to compile
